### ISSUE TITLE
Atualização para Laravel 5.6 e PHP 7

### ISSUE THREAD

**Issue by geidsonc** [Sysvale/libreclass#10]
O projeto foi construído com Laravel 4.2. Agora faz-se necessário atualização do framework e da versão do PHP para melhor desempenho e criar novas possibilidades de implementação de funcionalidades.

**Comment by khflab** [comment]
Beleza, então os primeiros passos:

- Novo branch para colocar a nova versão do Laravel
- Criar as migrations de acordo com o banco de dados da versão anterior
- Criar as models e ligar os relacionamentos
- Escolher/instalar um dashboard
- Criar view de login e todo o processo de Login

Acho que esse seria o primeiro milestone

**Comment by geidsonc** [comment]
A última tag no master está com laravel 8
