### ISSUE TITLE
Models e relacionamentos

### ISSUE THREAD

**Issue by khflab** [Sysvale/libreclass#13]
Depois das migrations, models e relacionamentos para deixar o eloquent ok

**Comment by jonas110** [comment]
Olá, Criei os Models presentes na pasta old_project e seus respectivos relacionamentos presentes na imagem abaixo.  Agora a cobra vai fumar :snake::smoking:
![576a6133-5e45-4d75-b219-7e5aa645708d](https://user-images.githubusercontent.com/19979665/38948160-1942dcc6-4315-11e8-89f6-60b80bbfbeda.jpeg)

**Comment by geidsonc** [comment]
Certo. Agora o próximo passo é criar Mutators também.
